- name: Install flatpak application deployment framework for desktop apps
  apt: pkg=flatpak
  become: yes

- name: Add the flathub remote
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: yes

- name: Install snap daemon
  apt: pkg=snapd
  become: yes

- name: Install ansible
  apt: pkg=ansible
  become: yes

- name: Add VirtualBox repository key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc
  become: yes

- name: Add VirtualBox repository
  apt_repository: repo='deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib non-free' update_cache=yes
  become: yes

- name: Install Dynamic Kernel Module Support
  apt: pkg=dkms
  become: yes

- name: Install VirtualBox
  apt: pkg=virtualbox-6.1
  become: yes

- name: Configure VirtualBox network access
  lineinfile:
    path: /etc/vbox/networks.conf
    line: "* 0.0.0.0/0 ::/0"
    create: yes
  become: yes

- name: Install vagrant
  apt: pkg=vagrant
  become: yes

- name: Download Terraform installation resource
  get_url: url=https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip dest=~/Installs/terraform_1.1.7_linux_amd64.zip checksum=sha256:e4add092a54ff6febd3325d1e0c109c9e590dc6c38f8bb7f9632e4e6bcca99d4

- name: Unarchive Terraform
  unarchive: src=~/Installs/terraform_1.1.7_linux_amd64.zip remote_src=yes dest=/tmp

- name: Install Terraform
  copy: src=/tmp/terraform dest=/usr/local/bin remote_src=yes mode=0755
  become: yes

- name: Install packer
  apt: pkg=packer
  become: yes

- name: Install awscli
  pip: name=awscli executable=pip3
  become: yes

- name: Install vim plugins
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
    - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
    - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}
