- name: Install flatpak application deployment framework for desktop apps
  ansible.builtin.apt:
    name: flatpak
  become: yes

- name: Add the flathub remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: yes

- name: Install snap daemon
  ansible.builtin.apt:
    name: snapd
  become: yes

- name: Install ansible
  ansible.builtin.apt:
    name: ansible
  become: yes

- name: Install vagrant
  ansible.builtin.apt:
    name: vagrant
  become: yes

- name: Download Terraform installation resource
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}.zip"
    dest: "~/Installs/terraform_1.1.7_linux_{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}.zip"

- name: Unarchive Terraform
  ansible.builtin.unarchive:
    src: "~/Installs/terraform_1.1.7_linux_{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}.zip"
    remote_src: yes
    dest: /tmp

- name: Install Terraform
  ansible.builtin.copy:
    src: /tmp/terraform
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
  become: yes

- name: Install packer
  ansible.builtin.apt:
    name: packer
  become: yes

- name: Install awscli
  ansible.builtin.apt:
    name: awscli
  become: yes

- name: Install vim plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: ~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
    - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
    - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}
