- name: Add non-free repository
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^deb http.* {{ ansible_distribution_release }} main'
    line: 'deb https://mirror.aarnet.edu.au/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main contrib non-free'
  become: yes

- name: Enabling 32-bit support
  command: dpkg --add-architecture i386
  become: yes

- name: Accept license
  debconf:
    name: steam
    question: steam/question
    value: I AGREE
    vtype: select
  become: yes

- name: Install steam
  apt: pkg=steam update_cache=yes
  become: yes

- name: Disable non-free repository
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^deb http.* {{ ansible_distribution_release }} main*'
    line: 'deb https://mirror.aarnet.edu.au/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main'
  become: yes
