- name: Download 1Password .deb
  get_url: url=https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb dest=~/Installs/1password-latest.deb checksum=sha256:22187f1c75b47587bb4ae54c65a0c8013c2e12f2233dc9d86ef44c2864bb7f5a

- name: Install 1Password
  apt: deb=/tmp/Installs/1password-latest.deb
  become: yes

- name: Install Gpick color picker
  apt: pkg=gpick
  become: yes

- name: Download boost note
  get_url: url=https://github.com/BoostIO/BoostNote-App/releases/download/v0.23.1/boost-note-linux.AppImage dest=~/Installs/boost-note-linux.AppImage checksum=sha256:ce588518472192b393173362acd3e7f0eb06c466b3aeeca6087d8e629173c3ff mode=u+x
