- name: Install bash completion
  ansible.builtin.apt:
    pkg: bash-completion
  become: true

- name: Install git
  ansible.builtin.apt:
    pkg: git-core
  become: true

- name: Setup terminal for git
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (GIT)"
    create: true
    mode: '0644'
    block: |
      if [ -f /usr/share/bash-completion/completions/git ]; then
          source /usr/share/bash-completion/completions/git
      fi

      if [ -f /usr/lib/git-core/git-sh-prompt ]; then
          source /usr/lib/git-core/git-sh-prompt
          export GIT_PS1_SHOWDIRTYSTATE=1 GIT_PS1_SHOWSTASHSTATE=1 GIT_PS1_SHOWUNTRACKEDFILES=1
          export GIT_PS1_DESCRIBE_STYLE=branch
          export PROMPT_COMMAND='__git_ps1 "\u@\h:\w" " \\\$ "'
          export GIT_PS1_SHOWCOLORHINTS=1
      fi

- name: Setup git colors
  ansible.builtin.blockinfile:
    path: ~/.gitconfig
    create: true
    mode: '0644'
    block: |
      [color]
        branch = auto
        diff = auto
        status = auto
      [color "branch"]
        current = yellow reverse
        local = yellow
        remote = green
      [color "diff"]
        meta = yellow bold
        frag = magenta bold
        old = red bold
        new = green bold
      [color "status"]
        added = yellow
        changed = green
        untracked = cyan

- name: Install GitHub CLI
  ansible.builtin.apt:
    pkg: gh
  become: true
