- name: Install htop for process monitoring
  ansible.builtin.apt:
    name: htop
  become: true

- name: Install smem for memory monitoring
  ansible.builtin.apt:
    name: smem
  become: true

- name: Install iftop for network monitoring
  ansible.builtin.apt:
    name: iftop
  become: true

- name: Install iotop for disk I/O monitoring
  ansible.builtin.apt:
    name: iotop
  become: true

- name: Install Wireshark
  ansible.builtin.apt:
    name: wireshark
  become: true

- name: Install TaskWarrior To-Do
  ansible.builtin.apt:
    name: taskwarrior
  become: true

- name: Install TaskWarrior terminal interface
  ansible.builtin.apt:
    name: vit
  become: true

- name: Install PlantUML diagramming tool
  ansible.builtin.apt:
    name: plantuml
  become: true

- name: Install cloc for counting lines of code
  ansible.builtin.apt:
    name: cloc
  become: true

- name: Install terminator terminal emulator
  ansible.builtin.apt:
    name: terminator
  become: true

- name: Create terminator configuration directory
  ansible.builtin.file:
    path: ~/.config/terminator
    state: directory

- name: Copy terminator configuration
  ansible.builtin.copy:
    src: terminator.config
    dest: ~/.config/terminator/config

- name: Install tmux terminal multiplexer
  ansible.builtin.apt:
    name: tmux
  become: true

- name: Install lshw for listing hardware details
  ansible.builtin.apt:
    name: lshw
  become: true

- name: Install Midnight Commander file manager
  ansible.builtin.apt:
    name: mc
  become: true

- name: Install curl
  ansible.builtin.apt:
    name: curl
  become: true

- name: Install whois
  ansible.builtin.apt:
    name: whois
  become: true

- name: Install HTTPie cURL wrapper
  ansible.builtin.apt:
    name: httpie
  become: true

- name: Install NCurses disk Usage utility
  ansible.builtin.apt:
    name: ncdu
  become: true

- name: Install wondershaper for limiting adapter bandwidth
  ansible.builtin.apt:
    name: wondershaper
  become: true

- name: Install locate
  ansible.builtin.apt:
    name: plocate
  become: true

- name: Install icdiff side by side diff tool
  ansible.builtin.apt:
    name: icdiff
  become: true

- name: Install expect for automating shell interaction
  ansible.builtin.apt:
    name: expect
  become: true

- name: Install fdupes for finding duplicate files on filesystem
  ansible.builtin.apt:
    name: fdupes
  become: true

- name: Install bc command line calculator
  ansible.builtin.apt:
    name: bc
  become: true

- name: Install xclip clipboard utility
  ansible.builtin.apt:
    name: xclip
  become: true

- name: Install jq json processor
  ansible.builtin.apt:
    name: jq
  become: true
