name: Test

on:
  workflow_dispatch: {}
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-debian-11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Provision
        uses: addnab/docker-run-action@v3
        with:
          image: debian:11-slim
          options: -v ${{ github.workspace }}:/work -w /work -e ANSIBLE_FORCE_COLOR=1
          shell: bash
          run: |
            apt-get update &&
            apt-get install -y sudo &&
            ./prepare.sh &&
            ansible-playbook -e "ansible_python_interpreter:'/usr/bin/python3'" -i "debian-11," -c local playbook.yml &&
            apt -y autoremove
        env:
          ANSIBLE_FORCE_COLOR: '1'

  setup-debian-12:
    runs-on: ubuntu-latest
    needs: setup-debian-11

    steps:
      - uses: actions/checkout@v2

      - name: Provision
        uses: addnab/docker-run-action@v3
        with:
          image: debian:12-slim
          options: -v ${{ github.workspace }}:/work -w /work -e ANSIBLE_FORCE_COLOR=1
          shell: bash
          run: |
            apt-get update &&
            apt-get install -y sudo &&
            ./prepare.sh &&
            ansible-playbook -e "ansible_python_interpreter:'/usr/bin/python3'" -i "debian-12," -c local playbook.yml &&
            apt -y autoremove
        env:
          ANSIBLE_FORCE_COLOR: '1'

  setup-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Provision
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:22.04
          options: -v ${{ github.workspace }}:/work -w /work -e ANSIBLE_FORCE_COLOR=1
          shell: bash
          run: |
            apt-get update &&
            apt-get install -y sudo &&
            export DEBIAN_FRONTEND=noninteractive &&
            export TZ=Etc/UTC &&
            apt-get install -y tzdata &&
            ./prepare.sh &&
            ansible-playbook -e "ansible_python_interpreter:'/usr/bin/python3'" -i "ubuntu," -c local playbook.yml &&
            apt -y autoremove
