name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Provision
        run: |
          ./prepare.sh &&
          ansible-playbook -e "ansible_python_interpreter:'/usr/bin/python3'" -i "localhost," -c local playbook.yml &&
          sudo apt -y autoremove
        env:
          ANSIBLE_FORCE_COLOR: '1'
