name: Test

on:
  workflow_dispatch: {}
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-debian:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Provision
        uses: addnab/docker-run-action@v3
        with:
          image: debian:11-slim
          options: -v ${{ github.workspace }}:/work -w /work -e ANSIBLE_FORCE_COLOR=1
          shell: bash
          run: |
            apt-get update &&
            apt-get install sudo &&
            ./prepare.sh &&
            ansible-playbook -e "ansible_python_interpreter:'/usr/bin/python3'" -i "debian," -c local playbook.yml &&
            apt -y autoremove
        env:
          ANSIBLE_FORCE_COLOR: '1'

  setup-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Provision
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:20.04
          options: -v ${{ github.workspace }}:/work -w /work -e ANSIBLE_FORCE_COLOR=1
          shell: bash
          run: |
            apt-get update &&
            apt-get install sudo &&
            ./prepare.sh &&
            ansible-playbook -e "ansible_python_interpreter:'/usr/bin/python3'" -i "ubuntu," -c local playbook.yml &&
            apt -y autoremove
